### PR TITLE
Compatibility with Python 3

### PR DESCRIPTION
**Pull request by ihaveamac**
Updated for master
Also minor cleanup: use with statements to open/close files

Tested with 3.6.4

### CODE REVIEW

**Comment by zoogie** [comment]
@ihaveamac would you be opposed to the idea of me making py2 and py3 separate scripts? Reason is two-fold: it would be easier for me to maintain, and it will keep the pyinstaller exe sizes down to a sane level (its already getting out of hand).
The disadvantage, of course, is an extra file and a little more clutter, but I think that's a reasonable sacrifice for the above benefits.

**Comment by ihaveamac** [comment]
I guess if you want that. trying to keep 2/3 compatibility in a single script without external dependencies can get pretty annoying.

**Comment by zoogie** [comment]
I chose to leave this one script since it's pretty much a completed project, so no maintenance worries.
Also, the pyinstaller exe blob actually shrank when running under python 3 so that was a pleasant surprise given my assumption it would grow with a hybrid script.

**Comment by ihaveamac** [comment]
compatibility with 2 and 3 in a single script can be a pain in the ass. I wish we could just leave 2.7 behind.

**Pull request merged**
